"""The tables the README publishes, written by the code that measured them.

Every table here is regenerated by `finishline report` and written between markers in
README.md. Nothing in them is typed by hand, because a results table somebody can edit is
a results table somebody can edit.
"""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from typing import Any

from finishline.backtest import score
from finishline.metrics import grade
from finishline.models import courses
from finishline.store import Dataset


def _minutes(seconds: float | None) -> str:
    return "-" if seconds is None else f"{seconds / 60.0:.1f}"


def _percent(fraction: float | None) -> str:
    return "-" if fraction is None else f"{fraction * 100:.0f}%"


def archive_table(dataset: Dataset) -> str:
    """What the archive turned out to hold once every page was read."""
    depths = dataset.depth_counts()
    rows = [
        ("Races read", f"{len(dataset.races) - len(dataset.failures):,}"),
        ("Finishes parsed", f"{dataset.finishes:,}"),
        ("Runners resolved", f"{len(dataset.resolved):,}"),
        (
            "Runners this refuses to tell apart, and will not publish",
            f"{len(dataset.ambiguous):,}",
        ),
        ("Runners with one finish", f"{depths['1']:,}"),
        ("Runners with two or three", f"{depths['2 to 3']:,}"),
        ("Runners with four or more", f"{depths['4 or more']:,}"),
        ("Pages that would not parse", f"{len(dataset.failures):,}"),
    ]
    lines = ["| | |", "|---|---:|"]
    lines += [f"| {label} | {value} |" for label, value in rows]
    return "\n".join(lines)


def course_table(
    fit: courses.Fit, profiles: Mapping[str, Mapping[str, Any]], *, show: int = 8
) -> str:
    """The hardest and easiest courses, and the grade the hills would need.

    Both ends, not just the hard end. A reader checking whether this is measuring anything
    real wants to see that the flat 5 km races come out flat, and the spread between the
    ends is the thing a course correction has to be worth.
    """
    ranked = sorted(fit.courses.values(), key=lambda c: -c.factor)
    if not ranked:
        return "_No course has enough finishes to measure yet._"

    lines = [
        "| Course | Finishes | Editions | Slower than flat | 95% CI "
        "| Grade that would explain it |",
        "|---|---:|---:|---:|---|---|",
    ]

    def row(measured: courses.CourseFactor) -> str:
        record = profiles.get(measured.course_id, {})
        explained = ""
        if "climb_m" in record:
            solved = grade.implied_grade(
                distance_m=float(record["distance_m"]),
                climb_m=float(record["climb_m"]),
                drop_m=float(record["drop_m"]),
                factor=measured.factor,
            )
            explained = (
                f"{solved:.1%} average, over the published {record['climb_m']:.0f} m of climb"
                if solved is not None
                else "**the published climb cannot explain it**"
            )
        return (
            f"| {measured.course_id} | {measured.finishes:,} | {measured.editions} "
            f"| {measured.percent:+.1f}% "
            f"| [{measured.low * 100:+.1f}, {measured.high * 100:+.1f}] | {explained} |"
        )

    lines += [row(measured) for measured in ranked[:show]]
    if len(ranked) > 2 * show:
        lines.append(f"| _... {len(ranked) - 2 * show} more_ | | | | | |")
    lines += [row(measured) for measured in ranked[-show:]]
    return "\n".join(lines)


def baseline_table(scored: Sequence[score.Scored], models: Sequence[str]) -> str:
    """Error and coverage per model per history-depth stratum, with intervals.

    Coverage sits beside error in every row, because a model that answers for the easy
    half of a field is not better than one that answers for all of it.
    """
    header = (
        "| Prior results | Runners | Model | Answered | MAE, minutes (95% CI) | "
        "Mean % error | Skill vs carry-forward |"
    )
    lines = [header, "|---|---:|---|---:|---|---:|---:|"]

    for label, _low, _high in score.STRATA:
        rows = [row for row in scored if score.stratum_of(row.depth) == label]
        if not rows:
            continue
        baseline = score.summarise(rows, models[0])
        total = baseline.runners
        for index, model in enumerate(models):
            summary = score.summarise(rows, model)
            interval = (
                "-"
                if summary.mae_seconds is None
                else f"{_minutes(summary.mae_seconds)} "
                f"({_minutes(summary.mae_low)} to {_minutes(summary.mae_high)})"
            )
            relative = score.skill(summary, baseline)
            lines.append(
                f"| {label if index == 0 else ''} | {total if index == 0 else ''} | "
                f"`{model}` | {_percent(summary.coverage)} | {interval} | "
                f"{_percent(summary.mape)} | "
                f"{'baseline' if index == 0 else _percent(relative)} |"
            )
    return "\n".join(lines)


def placing_table(scored: Sequence[score.Scored], models: Sequence[str]) -> str:
    """How well each model got the finishing order, averaged over races."""
    lines = [
        "| Model | Races | Mean absolute place error | Spearman, predicted vs actual |",
        "|---|---:|---:|---:|",
    ]
    races = sorted({row.race_id for row in scored})
    for model in models:
        gaps: list[float] = []
        correlations: list[float] = []
        for race_id in races:
            rows = [row for row in scored if row.race_id == race_id]
            gap, correlation = score.place_error(rows, model)
            if gap is not None and correlation is not None:
                gaps.append(gap)
                correlations.append(correlation)
        if not gaps:
            lines.append(f"| `{model}` | 0 | - | - |")
            continue
        lines.append(
            f"| `{model}` | {len(gaps)} | {sum(gaps) / len(gaps):.1f} | "
            f"{sum(correlations) / len(correlations):.3f} |"
        )
    return "\n".join(lines)


def replace_between(text: str, marker: str, table: str) -> str:
    """Put `table` between this marker's start and end tags, leaving the rest alone."""
    start, end = f"<!-- finishline:{marker} -->", f"<!-- finishline:end:{marker} -->"
    if start not in text or end not in text:
        raise ValueError(f"README has no {start} ... {end} block")
    head, rest = text.split(start, 1)
    _old, tail = rest.split(end, 1)
    return f"{head}{start}\n{table}\n{end}{tail}"
