"""The tables the README publishes, written by the code that measured them.

Every table here is regenerated by `finishline report` and written between markers in
README.md. Nothing in them is typed by hand, because a results table somebody can edit is
a results table somebody can edit.
"""

from __future__ import annotations

import statistics
from collections.abc import Mapping, Sequence
from typing import Any

from finishline.backtest import score
from finishline.conformal import coverage, split
from finishline.metrics import grade
from finishline.models import conditions, courses
from finishline.store import Dataset


def _minutes(seconds: float | None) -> str:
    return "-" if seconds is None else f"{seconds / 60.0:.1f}"


def _percent(fraction: float | None) -> str:
    return "-" if fraction is None else f"{fraction * 100:.0f}%"


def archive_table(dataset: Dataset) -> str:
    """What the archive turned out to hold once every page was read."""
    depths = dataset.depth_counts()
    rows = [
        ("Races read", f"{len(dataset.races) - len(dataset.failures):,}"),
        ("Finishes parsed", f"{dataset.finishes:,}"),
        ("Runners resolved", f"{len(dataset.resolved):,}"),
        (
            "Runners this refuses to tell apart, and will not publish",
            f"{len(dataset.ambiguous):,}",
        ),
        ("Runners with one finish", f"{depths['1']:,}"),
        ("Runners with two or three", f"{depths['2 to 3']:,}"),
        ("Runners with four or more", f"{depths['4 or more']:,}"),
        ("Pages that would not parse", f"{len(dataset.failures):,}"),
    ]
    lines = ["| | |", "|---|---:|"]
    lines += [f"| {label} | {value} |" for label, value in rows]
    return "\n".join(lines)


def course_table(
    fit: courses.Fit, profiles: Mapping[str, Mapping[str, Any]], *, show: int = 8
) -> str:
    """The hardest and easiest courses, and the grade the hills would need.

    Both ends, not just the hard end. A reader checking whether this is measuring anything
    real wants to see that the flat 5 km races come out flat, and the spread between the
    ends is the thing a course correction has to be worth.
    """
    ranked = sorted(fit.courses.values(), key=lambda c: -c.factor)
    if not ranked:
        return "_No course has enough finishes to measure yet._"

    lines = [
        "| Course | Finishes | Editions | Slower than flat | 95% CI "
        "| Grade that would explain it |",
        "|---|---:|---:|---:|---|---|",
    ]

    def row(measured: courses.CourseFactor) -> str:
        record = profiles.get(measured.course_id, {})
        explained = ""
        if "climb_m" in record:
            solved = grade.implied_grade(
                distance_m=float(record["distance_m"]),
                climb_m=float(record["climb_m"]),
                drop_m=float(record["drop_m"]),
                factor=measured.factor,
            )
            explained = (
                f"{solved:.1%} average, over the published {record['climb_m']:.0f} m of climb"
                if solved is not None
                else "**the published climb cannot explain it**"
            )
        return (
            f"| {measured.course_id} | {measured.finishes:,} | {measured.editions} "
            f"| {measured.percent:+.1f}% "
            f"| [{measured.low * 100:+.1f}, {measured.high * 100:+.1f}] | {explained} |"
        )

    lines += [row(measured) for measured in ranked[:show]]
    if len(ranked) > 2 * show:
        lines.append(f"| _... {len(ranked) - 2 * show} more_ | | | | | |")
    lines += [row(measured) for measured in ranked[-show:]]
    return "\n".join(lines)


def conditions_table(model: conditions.Fit | None, editions: int, skipped: int) -> str:
    """What the morning costs, and how sure of it the archive lets us be.

    A fresh clone has no weather cache, so this says so rather than failing: the table is
    regenerated by `finishline report` and the observations come from `finishline weather`.
    """
    if model is None:
        return (
            "_No conditions model yet. `finishline weather` fetches the observations and "
            "`finishline report` fills this in._"
        )

    lines = [
        f"Fitted on {model.editions} editions near St. John's airport, "
        f"{skipped} of {editions} excluded as too far from it or without an observation. "
        f"Explains **{model.explained * 100:.0f}%** of the edition-to-edition variance "
        f"within a course, leaving sd {model.residual_sd * 100:.2f}%.",
        "",
        "| Race length | Cost per degree above neutral | What a 20 C morning costs |",
        "|---|---:|---:|",
    ]
    for label, metres in (
        ("5 km", 5_000.0),
        ("10 km", 10_000.0),
        ("Tely 10", 16_093.0),
        ("Cape to Cabot 20 km", 20_000.0),
        ("marathon", 42_195.0),
    ):
        per_degree = model.temp_coefficient(metres) * 100
        at_twenty = model.temp_coefficient(metres) * (20.0 - conditions.NEUTRAL_TEMP_C) * 100
        lines.append(f"| {label} | {per_degree:+.2f}% | {at_twenty:+.1f}% |")

    low, high = model.intervals["temp_at_10km"]
    tail_low, tail_high = model.intervals["tailwind"]
    lines += [
        "",
        f"Neutral is {conditions.NEUTRAL_TEMP_C:.0f} C and "
        f"{conditions.NEUTRAL_WIND_KMH:.0f} km/h, which is the middle of this archive rather "
        "than a laboratory ideal.",
        "",
        "| Term | Estimate | 95% CI |",
        "|---|---:|---|",
        f"| Temperature at 10 km, per degree | {model.temp_at_reference * 100:+.3f}% "
        f"| [{low * 100:+.3f}, {high * 100:+.3f}] |",
        f"| Tailwind along the bearing, per km/h | {model.tailwind * 100:+.3f}% "
        f"| [{tail_low * 100:+.3f}, {tail_high * 100:+.3f}] |",
    ]
    return "\n".join(lines)


def baseline_table(scored: Sequence[score.Scored], models: Sequence[str]) -> str:
    """Error and coverage per model per history-depth stratum, with intervals.

    Coverage sits beside error in every row, because a model that answers for the easy
    half of a field is not better than one that answers for all of it.
    """
    header = (
        "| Prior results | Runners | Model | Answered | MAE, minutes (95% CI) | "
        "Mean % error | Skill vs carry-forward |"
    )
    lines = [header, "|---|---:|---|---:|---|---:|---:|"]

    for label, _low, _high in score.STRATA:
        rows = [row for row in scored if score.stratum_of(row.depth) == label]
        if not rows:
            continue
        baseline = score.summarise(rows, models[0])
        total = baseline.runners
        for index, model in enumerate(models):
            summary = score.summarise(rows, model)
            interval = (
                "-"
                if summary.mae_seconds is None
                else f"{_minutes(summary.mae_seconds)} "
                f"({_minutes(summary.mae_low)} to {_minutes(summary.mae_high)})"
            )
            relative = score.skill(summary, baseline)
            lines.append(
                f"| {label if index == 0 else ''} | {total if index == 0 else ''} | "
                f"`{model}` | {_percent(summary.coverage)} | {interval} | "
                f"{_percent(summary.mape)} | "
                f"{'baseline' if index == 0 else _percent(relative)} |"
            )
    return "\n".join(lines)


def paired_error_table(scored: Sequence[score.Scored], model: str, other: str) -> str:
    """One model against another on the same runners, by history depth.

    Two MAE intervals in the table above can overlap while one model is consistently better
    on the same runners; this is the paired test, resampling races.
    """
    lines = [
        f"`{model}` against `{other}` on the same runners. The difference is in mean absolute "
        "error as a percent of each runner's own finish time; negative favours "
        f"`{model}`, and the 95% CI resamples races.",
        "",
        f"| Prior results | Runners | Races | MAE, minutes, `{model}` vs `{other}` "
        "| Difference, points of a finish time (95% CI) |",
        "|---|---:|---:|---|---|",
    ]
    for label, _low, _high in score.STRATA:
        rows = [row for row in scored if score.stratum_of(row.depth) == label]
        paired = score.paired_error(rows, model, other)
        if paired is None:
            continue
        point, low, high = paired.difference
        lines.append(
            f"| {label} | {paired.runners:,} | {paired.races} "
            f"| {_minutes(paired.model_mae_seconds)} vs {_minutes(paired.other_mae_seconds)} "
            f"| {point:+.2f} ({low:+.2f} to {high:+.2f}) |"
        )
    return "\n".join(lines)


def placing_table(scored: Sequence[score.Scored], models: Sequence[str]) -> str:
    """How well each model got the finishing order, averaged over races."""
    lines = [
        "| Model | Races | Mean absolute place error | Spearman, predicted vs actual |",
        "|---|---:|---:|---:|",
    ]
    races = sorted({row.race_id for row in scored})
    for model in models:
        gaps: list[float] = []
        correlations: list[float] = []
        for race_id in races:
            rows = [row for row in scored if row.race_id == race_id]
            gap, correlation = score.place_error(rows, model)
            if gap is not None and correlation is not None:
                gaps.append(gap)
                correlations.append(correlation)
        if not gaps:
            lines.append(f"| `{model}` | 0 | - | - |")
            continue
        lines.append(
            f"| `{model}` | {len(gaps)} | {sum(gaps) / len(gaps):.1f} | "
            f"{sum(correlations) / len(correlations):.3f} |"
        )
    lines += ["", paired_placing_table(scored, models)]
    return "\n".join(lines)


def paired_placing_table(scored: Sequence[score.Scored], models: Sequence[str]) -> str:
    """Each model against the first, ranked over the runners both answered for.

    The table above ranks every model among its own runners, which puts the whole field,
    newcomers included, in front of a model that answers for everybody and only the runners
    with a history in front of carry-forward. This one is the like-for-like comparison.
    """
    baseline = models[0]
    lines = [
        f"The same runners: each model against `{baseline}`, both ranked among the runners "
        f"both answered for in each race (races with at least "
        f"{score.PAIRED_PLACING_MINIMUM} of them). Negative place error and positive "
        "Spearman differences favour the model; the 95% CI resamples races.",
        "",
        f"| Model | Races | Runners | Place error, model vs `{baseline}` | Difference (95% CI) "
        f"| Spearman, model vs `{baseline}` | Difference (95% CI) |",
        "|---|---:|---:|---|---|---|---|",
    ]
    for model in models[1:]:
        paired = score.paired_placing(scored, model, baseline)
        if paired is None:
            lines.append(f"| `{model}` | 0 | 0 | - | - | - | - |")
            continue
        gap, gap_low, gap_high = paired.gap_difference
        rho, rho_low, rho_high = paired.spearman_difference
        lines.append(
            f"| `{model}` | {paired.races} | {paired.runners:,} "
            f"| {paired.gap:.1f} vs {paired.baseline_gap:.1f} "
            f"| {gap:+.1f} ({gap_low:+.1f} to {gap_high:+.1f}) "
            f"| {paired.spearman:.3f} vs {paired.baseline_spearman:.3f} "
            f"| {rho:+.3f} ({rho_low:+.3f} to {rho_high:+.3f}) |"
        )
    return "\n".join(lines)


def coverage_table(
    summaries: Mapping[float, Sequence[coverage.Coverage]],
    model: str | None,
    *,
    assumption: bool = True,
) -> str:
    """How often the model's intervals held, raw and after conformal adjustment.

    The assumption goes in the table's own text, because a coverage number read without it
    is a promise the method does not make.
    """
    if model is None:
        return (
            "_No saved model run matches the current code and data, so there are no intervals "
            "to check yet. `finishline backtest --hierarchical` produces one._"
        )
    lines = [
        f"`{model}`, every race from 2024 on. Each race's intervals are adjusted using only "
        "races dated before it, separately for each history depth. Coverage is the share of "
        "runners whose finish fell inside; the 95% CI resamples races, not runners, because "
        "runners in one race share its morning.",
        "",
        "| Prior results | Level | Runners checked | Races | Model's own interval | "
        "After conformal | Median width, minutes (own to conformal) |",
        "|---|---:|---:|---:|---|---|---|",
    ]

    def rate(point: float | None, low: float | None, high: float | None) -> str:
        if point is None or low is None or high is None:
            return "-"
        return f"{point * 100:.0f}% ({low * 100:.0f} to {high * 100:.0f})"

    for level in sorted(summaries):
        for summary in summaries[level]:
            checked = summary.rows - summary.unadjusted
            width = (
                "-"
                if summary.raw_width is None or summary.conformal_width is None
                else f"{summary.raw_width / 60:.1f} to {summary.conformal_width / 60:.1f}"
            )
            lines.append(
                f"| {summary.stratum} | {level * 100:.0f}% | {checked:,} | {summary.races} | "
                f"{rate(summary.raw, summary.raw_low, summary.raw_high)} | "
                f"{rate(summary.conformal, summary.conformal_low, summary.conformal_high)} | "
                f"{width} |"
            )
    if not assumption:
        return "\n".join(lines)
    lines += [
        "",
        "**The assumption.** Conformal coverage is guaranteed on average over races within a "
        "history-depth group, provided a new race's errors look like the earlier races' "
        "errors (exchangeability). It is not a promise about any one runner or any one race, "
        "and it fails when a race meets conditions or a field the earlier races did not: a "
        "gale on Signal Hill is exactly that. The first races of the backtest have too few "
        f"earlier errors to calibrate on (under {split.MIN_CALIBRATION} per group) and are "
        "left out of this table rather than given an interval nobody could trust.",
    ]
    return "\n".join(lines)


def replace_between(text: str, marker: str, table: str) -> str:
    """Put `table` between this marker's start and end tags, leaving the rest alone."""
    start, end = f"<!-- finishline:{marker} -->", f"<!-- finishline:end:{marker} -->"
    if start not in text or end not in text:
        raise ValueError(f"README has no {start} ... {end} block")
    head, rest = text.split(start, 1)
    _old, tail = rest.split(end, 1)
    return f"{head}{start}\n{table}\n{end}{tail}"


# What a reader means by a race length, and the metres that fall under it. The bands are wide
# enough that one course does not become its own row and narrow enough that a 5 km and a
# marathon never share one.
DISTANCE_BANDS: tuple[tuple[str, float, float], ...] = (
    ("5 km", 0.0, 5500.0),
    ("8 km", 5500.0, 9000.0),
    ("10 km", 9000.0, 12000.0),
    ("16 km (the Tely 10)", 12000.0, 17000.0),
    ("20 km", 17000.0, 25000.0),
    ("Half marathon", 25000.0, 30000.0),
    ("Marathon", 30000.0, 50000.0),
)


def distance_table(
    scored: Sequence[score.Scored], model: str, distances: Mapping[str, float]
) -> str:
    """One model's error by race length, in minutes and as a share of a finish time.

    An average error in minutes is not one claim: the same model is out by a minute and a half
    over 5 km and by a quarter of an hour over a marathon, and the honest common measure is the
    share of the runner's own finish time. Both are here, for the whole field and for the
    runners the archive knows well, because a race director reads the minutes and a runner
    comparing this with a race calculator reads the percent.
    """
    rows = [row for row in scored if row.model == model and row.predicted is not None]
    lines = [
        f"`{model}`, every race from 2024 on, grouped by race length. The middle column pair is "
        "the whole field, the right-hand pair the runners with four or more prior results. "
        "The percent is of each runner's own finish time.",
        "",
        "| Race length | Runners | Middle of the field | MAE, all | % of time, all "
        "| MAE, 4+ races | % of time, 4+ |",
        "|---|---:|---:|---:|---:|---:|---:|",
    ]
    for label, low, high in DISTANCE_BANDS:
        band = [
            row
            for row in rows
            if low <= distances.get(row.race_id, -1.0) < high
        ]
        if not band:
            continue
        deep = [row for row in band if score.stratum_of(row.depth) == "4 or more"]
        everyone = score.summarise(band, model)
        experienced = score.summarise(deep, model) if deep else None
        median = statistics.median(row.actual for row in band)
        lines.append(
            f"| {label} | {len(band):,} | {_minutes(median)} "
            f"| {_minutes(everyone.mae_seconds)} | {_percent(everyone.mape)} "
            f"| {'-' if experienced is None else _minutes(experienced.mae_seconds)} "
            f"| {'-' if experienced is None else _percent(experienced.mape)} |"
        )
    return "\n".join(lines)


def speed_table(
    scored: Sequence[score.Scored],
    model: str,
    metres: Mapping[str, float],
    field: Mapping[str, Sequence[float]],
) -> str:
    """One model's error by race length and by where a runner finishes in their own race.

    The front of a field is predicted more tightly than the back of it, in minutes and as a
    share of a finish time both, and a single average hides that. Runners with four or more
    prior results only, so the three columns differ by speed and not by how much history each
    group happens to have.
    """
    from finishline.publish import showcase

    groups = showcase.distance_groups(scored, metres, field, model)
    rows = groups["rows"]
    headings = " | ".join(
        f"{label} ({note})" for _key, label, note, _low, _high in showcase.SPEED_GROUPS
    )
    lines = [
        f"`{model}`, every race from 2024 on, for runners with four or more prior results, by "
        "race length and by where they finished in their own race. Each cell is the mean "
        "absolute error in minutes and as a percent of the runner's own finish time.",
        "",
        f"| Race length | {headings} |",
        "|---|---|---|---|",
    ]
    ordered = [label for label, _low, _high in DISTANCE_BANDS]
    for label in ordered:
        cells = []
        for key, _label, _note, _low, _high in showcase.SPEED_GROUPS:
            found = next((row for row in rows.get(key, []) if row["label"] == label), None)
            if found is None:
                cells.append("-")
            else:
                share = found["mape"] * 100
                cells.append(
                    f"{found['mae_min']:.1f} min, {share:.1f}% ({found['runners']:,})"
                )
        if all(cell == "-" for cell in cells):
            continue
        lines.append(f"| {label} | " + " | ".join(cells) + " |")
    return "\n".join(lines)
